server:
  port: 9094
spring:
  application:
    name: authentication-service
    
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
     exposure :
      include : "*"
  endpoint:
    health:
      show-details: always
     
resilience4j:
  circuitbreaker:
    instances:
      gameplayMechanicsServiceBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
